### ISSUE TITLE
Ausführungsschwierigkeiten

### ISSUE THREAD

**Issue by ChaoticSomeone** [ChaoticSomeone/ooen_mining#2]
Lässt sich das Programm nicht ausführen bitte folgende Schritte durchführen:
1) Terminal im Projektordner öffnen
2) sicherstellen, dass PIP auf der neusten Version ist, wenn nicht, dann bitte die neue Version installieren
3) Den Befehl ```pip install virtualenv``` ausführen, welcher einen Ordner erzeugt, welcher ```venv``` oder ```virtualenv``` heißt
4) Die Datei ```activate``` (ohne Dateierweiterung) im Verzeichnis <Projektornder>/venv/Scripts/ bzw. <Projektornder>/virtualenv/Scripts/ über den Terminal ausführen
5) Den Befehl ```pip install bs4``` ausführen
6) Den Befehl ```python scraper.py``` ausführen

Sollte es trotzdem nicht funktionieren, dann weiß ich auch ned wirklich weiter

**Comment by cannondale-f500** [comment]
Danke für den Hinweis. Ich wusste leider nicht worauf ich zu achten habe, um festzustellen, dass das Programm wirklich läuft und auch tut, was es soll. Ich führe es gerade aus und warte die ersten JSON-Dateien ab und stelle sie euch auf [https://github.com/cannondale-f500/ooen_output](url) wieder bereit. Es hat von anfang an gut funktioniert und es ist momentan die letztverfügbare PIP Version inalliert.
Die momentane Auslastung liegt Gesamt bei etwa 25% und liegt bei einem Kern bei fast 100%. Der RaspberyPI 3B+ läuft momentan nur für euer Programm durch.

**Comment by cannondale-f500** [comment]
Die momentane Ausgabe des Programmes lautet:
0 neue Artikel gefunden und gespeichert!
Warten auf Cooldown...

**Comment by ChaoticSomeone** [comment]
Scheint als würde das Problem nur unter Windows bestehen (ich entwickle das Program ja auf Windows 11). Man merkt, dass das Program nicht funktioniert, wenn es sich von Anfang an nicht ausführen lässt oder es während der Ausführung unterwartet beendet wird.

**Comment by cannondale-f500** [comment]
Funktioniert das Programm wie vorgesehen? Ich habe mal ein update des json files upgeloaded.

**Comment by ChaoticSomeone** [comment]
Scheint einwandfrei zu funktionieren

**Comment by cannondale-f500** [comment]
Ich habe aufgrund eines Absturzes von qt-creator den RPI neu starten müssen. Leider bekomme ich folgende Fehlermeldung beim erneuten Ausführen des Scripts:
python3 scraper.py 
...  Traceback (most recent call last):
  File "../ooen_mining-main/scraper.py", line 90, in <module>
    dataLine = s.find("div", class_="text-teaser text-darkgrey mb-32").text.replace("\n", "").replace("\t", "").replace(" ", "").strip().split(",")
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by http9** [comment]
AttributeError wurde gefixt

**Comment by cannondale-f500** [comment]
Die Ausführung wurde abgebrochen:
16 neue Artikel gefunden und gespeichert!
.    Traceback (most recent call last):
  File "/home/thomass/Downloads/ooen_mining-main/scraper.py", line 119, in <module>
    "date": dates[i],
IndexError: list index out of range
